# -*- coding: utf-8 -*-
"""Untitled81.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k9YaypKOiGuius13dkaBn6RJXpAvU4jv
"""

from flask import Flask

app=Flask()

@app.route("/")
def Hola_mundo():
  return "Hola a todos"